name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Assuming you have a requirements.txt file

      - name: Run pytest
        run: pytest

      - name: Check for test failures
        if: failure()
        run: echo "Tests failed!" && exit 1 

      - name: Tests passed!
        if: success()
        run: echo "All tests passed!"