name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies (if needed)
        if: steps.setup-python.outcome == 'success'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # If you have a requirements file

      - name: Build your application (if needed)
        run: |
          # Add commands to build your application if necessary.
          echo "Building application..." # Replace with your actual build commands
          # Example: python manage.py collectstatic --noinput

      - name: Deploy to Render
        uses: render-oss/github-action@v1 # Use the Render GitHub Action
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }} 