name: Deploy to Render
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Delay to avoid overlapping deploys
        run: sleep 120

      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cult1da3esus73b3enk0?key=jH7Z_69dKDc"
